# Generated by Django 5.1.2 on 2024-10-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('link', models.TextField()),
                ('processor', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('ratings', models.CharField(max_length=200)),
                ('star', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
            ],
        ),
    ]
