# Generated by Django 5.1.2 on 2024-10-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_star_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_float',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
