# Generated by Django 5.1.2 on 2024-10-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_star_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_float',
            field=models.CharField(default='1_1', max_length=3),
        ),
    ]
