# Generated by Django 5.1.2 on 2024-10-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
